### ISSUE TITLE
Unclickable totems

### ISSUE THREAD

**Issue by joachimBrindeau** [CDawg/totemcaddy#3]
Hello!

I might be missing something but I can't figure out why the totems are unclickable:
![image](https://user-images.githubusercontent.com/6870905/144738354-350f0841-f10b-435c-a307-46d0b3ce7e40.png)
![image](https://user-images.githubusercontent.com/6870905/144738378-ef28ae37-0754-42c0-aeb9-290c04e01270.png)

Thanks for your help!
Joachim-Sulfuron (Horde - EU)

**Comment by CDawg** [comment]
Hi joachimBrindeau,
Are you using a different raid frame UI?
It looks like ElvUI?
I might need to diagnose what's going on with the UI that you are using.

**Comment by joachimBrindeau** [comment]
Indeed!
Elvui's latest version, out of the box.
Let me know if I can do anything!

**Comment by CDawg** [comment]
There were several bugfixes and changes made, to make the frame compatible with ElvUI users. I'm not able to reproduce the problem.

**Comment by joachimBrindeau** [comment]
I think I know.
Could it be that my client is in french so it doesn't know the name of the spell?
If yes, could you please tell me what file to translate?

**Comment by CDawg** [comment]
Ah, that might be it yes.
If i can convert the names, I can add a locale for other languages.

**Comment by CDawg** [comment]
Hi [joachimBrindeau](https://github.com/joachimBrindeau)
The localization for French Language was added. The Options menu is still in English. I need to get a translator.
However, all the functionality, timers, and spells are now in each of the respective languages :)
Can you please confirm. Thanks!

**Comment by joachimBrindeau** [comment]
Thank you very much!
It works!

If you need me to translate something just let me know.
