### ISSUE TITLE
[enhancement] Locale independency

### ISSUE THREAD

**Issue by Road-block** [CDawg/totemcaddy#4]
Out of curiosity, is there any reason why spellnames are not [cached using API](https://wowpedia.fandom.com/wiki/API_GetSpellInfo)?

Then all the necessary spells could be gotten from their ids and be valid for all game clients.

**Comment by CDawg** [comment]
Hey Road-block,
Using the spell ID causes issues with spell ranks.

**Comment by CDawg** [comment]
Reordered all the IDs for localization and added all spell IDs with ranks.
